= fsm-benchmarks

This repo contains benchmarks for C++ state machine libraries.

It has been originally created to test various optimizations of the https://github.com/boostorg/msm[Boost MSM] library.


== Benchmark scenarios

*Header inclusion:*

No instantiation of a state machine, only the headers of the library are included.


*Large state machine:*

Similar benchmark as tested in https://github.com/fgoujeon/fsm-benchmark[fsm-benchmark], but with a few differences.

The state machine gets constructed and processes events for 1000 iterations. The events trigger transitions and internal transitions in alternation. In total it processes:

* 25000000 transitions
* 25000000 internal transitions
* 5000000 internal transitions via the event pool (events enqueued every 5th transition)


*Large hierarchical state machine:*

Extension of the large state machine benchmark with a hierarchical structure of 3 state machines:

* fsm0 is the root state machine
* fsm1 is contained in fsm0
* fsm2 is contained in fsm1

One iteration in this benchmark runs as follows:

* process events
* enter fsm1 and process events
* enter fsm2 and process events
* exit fsm2 and exit fsm1

The events handled by each state machine overlap with each other to simulate transition conflicts. Each state machine processes the same amount of events as in the large state machine benchmark.


== Tested libraries

The following libraries are benchmarked:

*MSM:*

MSM is used with 3 back-ends `back`, `back11` and `backmp11`.
The back-end `backmp11` is a recent addition. For more details about the applied optimizations and changes to previous back-ends take a look at the https://github.com/boostorg/msm/blob/develop/include/boost/msm/backmp11/README.md[backmp11's README].

Only the functor frontend is used in the benchmarks. The following backend configurations are tested:

* `back` backend with `favor_runtime_speed` and `favor_compile_time` compile policies
* `back11` backend
* `backmp11` backend with `favor_runtime_speed` and `favor_compile_time` compile policies

Last run was done on commit 5f8422e8316ffeed8163795c6439d88b9a30b191.


*SML:*

https://github.com/boost-ext/sml[SML] is tested with a default configuration.

Last run was done on commit d0b0df7d39d05c6d31db3aebe64990e00cc08bd2.


== Benchmark results

System used for running the benchmarks:

* Intel i7-6700K @4GHZ, 32 GB RAM
* Clang 19.1.4, RelWithDebInfo, C++20
* CUs are compiled one-by-one except the multi_cu benchmark for MSM with `backmp11` & `favor_compile_time`


*Header inclusion*

[width=67%, cols="3,1,1", options="header"]
|=======================================================
|                             | Compile / sec | RAM / MB 
| back                        | 2.3           | 224
| back_favor_compile_time     | 2.3           | 224
| back11                      | 2.3           | 224
| backmp11                    | 0.6           | 126
| backmp11_favor_compile_time | 0.7           | 131
| sml                         | 0.1           | 95
|=======================================================


*Large state machine*

[width=80%, cols="3,1,1,1", options="header"]
|=======================================================================
|                             | Compile / sec | RAM / MB | Runtime / sec
| back                        | 16            | 953      | 2.8
| back_favor_compile_time     | 21            | 1000     | 3.3
| back11                      | 40            | 2794     | 2.7
| backmp11                    | 3             | 217      | 1.1
| backmp11_favor_compile_time | 3             | 205      | 6.0
| sml                         | 3             | 207      | 0.5
|=======================================================================


*Large hierarchical state machine*

[width=80%, cols="3,1,1,1", options="header"]
|================================================================================
|                                      | Compile / sec | RAM / MB | Runtime / sec
| back                                 | 62            | 2849     | 13.4
| back_favor_compile_time              | 73            | 2551     | > 300
| backmp11                             | 9             | 360      | 5.3
| backmp11_favor_compile_time          | 6             | 273      | 20.3
| backmp11_favor_compile_time_multi_cu | 4             | ~907     | 20.6
| sml                                  | 11            | 436      | 2.9
|================================================================================
